### ISSUE TITLE
In progress banner?

### ISSUE THREAD

**Issue by ivirshup** [scverse/scverse.github.io#13]
Could we add a banner or note that says this is a draft website for a draft organization until we launch?

Ideally it could look [something like this](http://textfiles.com/underconstruction/), but I'm flexible.

**Comment by gtca** [comment]
@ivirshup, I went for a less animated version with a red persistent banner on top. If that's fine, should be ready to be merged.

**Comment by ivirshup** [comment]
I can't seem to see the build artifact (ping @grst), but I'm happy for you to do this however you want

> I went for a less animated version

😢

**Comment by gtca** [comment]
Is the section `Actifacts` [on this page](https://github.com/scverse/scverse.github.io/actions/runs/1806784902) not visible to you?..

**Comment by ivirshup** [comment]
Ah yeah, can see that now. I don't see a banner though.

But also links seem absolute, so I can't click on much either, which could be relevant.

**Comment by gtca** [comment]
- I updated the PR but having checked the artifact, it somehow lacks some of the styles that I see when I deploy the same PR locally...
- I think it makes sense to serve it (e.g. with `python -m http.server`), the links should also work then.
