### ISSUE TITLE
Nav bar

### ISSUE THREAD

**Issue by adamgayoso** [scverse/scverse.github.io#20]
I think it would be nice to have a sticky nav, as well as hamburger menu for mobile!

**Comment by ivirshup** [comment]
Hamburger menu is set up, but font size does is not scaling well for mobile

**Comment by ivirshup** [comment]
@gtca you seemed against stick nav. Could you elaborate on this?

**Comment by gtca** [comment]
@ivirshup that's a global problem with mobile, probably need to remove the respective stuff from the styles and to attempt to rely on Bootstrap on that more...

No strong opinions on the stick nav bar but vertical space is _expensive_ and now more and more pages don't use the sticky bar. Just some random examples: [1][github] (lol), [2][deno], [3][deepmind], — which arguably live well with a non-sticky one. 

[github]: https://github.com/
[deno]: https://deno.land/
[deepmind]: https://www.deepmind.com/

**Comment by ivirshup** [comment]
Closing since we have a nav bar, improvements could still be made in future though.
