### ISSUE TITLE
Jobs page

### ISSUE THREAD

**Issue by Zethson** [scverse/scverse.github.io#28]
Suggested by @adamgayoso 
I have mixed feelings.

1. Jobs which we provide and pay for? Yes, they should go there
2. Jobs by other institutions/companies? Nah, let's not handle those. There are enough job boards out there. However, I could see us open a Zulip job stream where everyone can post their jobs without us moderating.

**Comment by ivirshup** [comment]
> However, I could see us open a Zulip job stream where everyone can post their jobs without us moderating.

I'd be pro this

> Jobs which we provide and pay for? 

Anti this. I don't think we're going to be doing enough hiring in the near future for this to be worth any effort. There are also many other job boards out there.

**Comment by adamgayoso** [comment]
It would be nice as a landing page to share the description.

**Comment by Zethson** [comment]
Think that this is out of scope for now so I'm gonna close it. We can reopen it if we feel like it's going to be necessary.
