### ISSUE TITLE
Add scirpy

### ISSUE THREAD

**Issue by ivirshup** [scverse/scverse.github.io#3]
Any suggestions for how @grst?

**Comment by grst** [comment]
What's your definition of "core" projects? Is it all "official" scverse repos, or just the core core everything is based on, like anndata and scanpy? 

If you want me to put it under core, I can put a PR together similar to #4.

**Comment by ivirshup** [comment]
"Core" is pretty much everything we're going to put under this org right now.

Basically it's tools that method packages can rely on. So I'd say `scirpy` is core since it's a toolkit for working with T/ B cell receptors. It handles things like IO, having a representation, and essential preprocessing/ QC.

**Comment by grst** [comment]
I think this can be closed as @gtca added the relevant changes.

**Comment by Zethson** [comment]
Think this includes moving the repository into the scverse organization?

**Comment by grst** [comment]
I understood this is just for the website. The scvi-tools issue has been closed, anyway. 

cf https://github.com/scverse/governance/issues/8
