### ISSUE TITLE
Add link to youtube channel

### ISSUE THREAD

**Issue by ivirshup** [scverse/scverse.github.io#5]
Could be a badge or could go in a "learning" section https://www.youtube.com/channel/UCpsvsIAW3R5OdftJKKuLNMA

Does youtube do nice URLs?

**Comment by gtca** [comment]
There is a YouTube badge that I commented out at the moment (it's just in the `layouts/index.html`).
Can get it back?

It's also among the links to different resources in the current version of the footer.

I think there are custom channel URLs but there are [conditions](https://support.google.com/youtube/answer/2657968?hl=en) to be met.

**Comment by ivirshup** [comment]
> Can get it back?

Sure! I don't think I like badges for these things in general (something bigger would be nice), but this works until we have different solution.

> It's also among the links to different resources in the current version of the footer.

I think we should have links to various platforms easy to reach from the top of the landing.

**Comment by gtca** [comment]
> I think we should have links to various platforms easy to reach from the top of the landing.

I'd say both? For the links at the top of the landing, github, twitter and (now) youtube are there, and I'd add discourse and discord (?) when we settle on them. That should be about it, I think?Seems like shields are good enough for this purpose for now.
