### ISSUE TITLE
Tutorials page?

### ISSUE THREAD

**Issue by ivirshup** [scverse/scverse.github.io#6]
It would be nice to have a page (organized somewhat by topic) pointing to selected tutorials for our packages and ecosystem.

Does that live here, or do we want to use something more `sphinx` like for it?

Examples/ inspo:

* [Seurat](https://satijalab.org/seurat/articles/get_started.html)
* [Bioconductor OSCA](https://bioconductor.org/books/release/OSCA/)
* [SciML Tutorials](https://tutorials.sciml.ai)
* [pyviz](https://examples.pyviz.org)
* [observable tutorials](https://observablehq.com/tutorials)
* [Adobe Illustrator](https://helpx.adobe.com/illustrator/tutorials.html)

**Comment by mbuttner** [comment]
Yes, I think it's a good idea to link some of the tutorials here. I suggested to @ivirshup that we add the scanpy tutorials from the scanpy workshop here, even though scanpy has its own list of tutorials elsewhere. I think that it is easiest to wrap tutorials as separate github project under the hood of scverse.

**Comment by gtca** [comment]
Just to give it a push, I've added a plain list of some tutorials in 4fbf724f21cce5c5418965329f5520cdbb389bc3: https://scverse.org/tutorials/.
It might make sense to collect more tutorials indeed and group them into sections (e.g. [Observable tutorials linked above](https://observablehq.com/tutorials)).

**Comment by mbuttner** [comment]
Alright, I have created a PR with the scanpy workshop notebooks to this repo https://github.com/scverse/scverse.github.io/pull/16
Not sure whether it fits here. Feel free to move it elsewhere.

**Comment by gtca** [comment]
Thanks @mbuttner, that's great!
I've been wondering what would be the best place for these and potentially more tutorials in the long run.
At least the two options I can see are
1. [scanpy-tutorials](https://github.com/theislab/scanpy-tutorials),
2. a new repo like [scverse-tutorials](https://github.com/scverse/scverse-tutorials) that we'll use for content like this.

What do you think and what options would you be strongly up for or against?

**Comment by mbuttner** [comment]
Thanks for looking at this! I actually think that creating a new repo like scverse-tutorials would be the best place for this as it is kind of independent from theislab now.

**Comment by Zethson** [comment]
I think that it would be easier to start out with keeping all tutorials in the respective tools (e.g. Maren's PR should imo go against scanpy docs).    
We can easily add a page on the website which looks like Seurat's tutorials page using sphinx-gallery or whatever custom solution we will use. This will then link to the respective tutorials of the respective tools.

At a later step we can try to consolidate the tutorials with a more sophisticated plan -> scverse tutorials repository maybe.

**Comment by ivirshup** [comment]
I agree with @Zethson. 

I think setting up a better system for rendering tutorials is a priority. I'd rather not fracture where the tutorials are kept for now so there are fewer places we need to implement a new system.

**Comment by mbuttner** [comment]
OK, sure. So I'll put the PR against the scanpy tutorials then. I would be happy to have an "scverse tutorials" repo at some point, too.
