### ISSUE TITLE
preview PR builds on netlify

### ISSUE THREAD

**Issue by grst** [scverse/scverse.github.io#63]
I previously set-up that for each PR the rendered page can be downloaded as a zip-artifact.

I now found an even better way. It is quite simple to deploy every PR to a temporary netlify instance. See https://github.com/omnideconv/immunedeconv/pull/108#issuecomment-1173843270 for an example and [here](https://github.com/omnideconv/immunedeconv/blob/6329e3e96aa132c93e399cd1ed56e1f5fa23ce6b/.github/workflows/pkgdown.yml#L51-L61) for the code. 

LMK if you want this, then I'll set it up.

**Comment by ivirshup** [comment]
Just seeing this now, but this would be great. This would also be great for another project I'm working on. How hard is setting up the netlify end?

**Comment by grst** [comment]
very easy. Basically just login with github single sign on, create a new project and you are good to go!

**Comment by ivirshup** [comment]
I think I got it working, but it's not clear to me if it's going to make a unique deploy per PR: ivirshup/ngff#1

**Comment by grst** [comment]
yes, the URL is unique per PR

**Comment by ivirshup** [comment]
If we were to set this up here, should we use some shared netlify account?

We could go for their [free open source tier](https://www.netlify.com/legal/open-source-policy/?_ga=2.238552256.1362864358.1665497871-1208339632.1665497871)

**Comment by grst** [comment]
How about logging in with the scverse bot github account?

Do we need anything special? The standard account seemed already generous
for pr builds

**Comment by ivirshup** [comment]
> scverse bot github account

Huh. I think this got set up while I was out with covid, so I don't think I'm familiar. Maybe PM me/ message core about login details/ docs?

> Do we need anything special?

Really just the ability for more than one of us to manage it.

**Comment by ivirshup** [comment]
I think this is done. Reopen if not
