### ISSUE TITLE
Links to ecosystem packages aren't working

### ISSUE THREAD

**Issue by Zethson** [scverse/scverse.github.io#76]
I expect to be forwarded to some website of the scverse ecosystem tool if I click on any of the package names. They are clickable after all but only forward again to https://scverse.org/packages/

**Comment by ivirshup** [comment]
We were trying to access `"package_home"` instead of `"project_home"`

Probably happened when we renamed from project to packages.

btw, I think this is worth an @ in future @Zethson 😉
