### ISSUE TITLE
About pages seem to activate the newly added packages dropdown

### ISSUE THREAD

**Issue by gtca** [scverse/scverse.github.io#79]
<img width="856" alt="image" src="https://user-images.githubusercontent.com/32863903/214871948-8e29d564-2a69-404d-9022-aba98a378884.png">

Not immediately clear why that happens but maybe you have some ideas, @ivirshup?..

**Comment by ivirshup** [comment]
Dangers of copy and paste: #80

**Comment by gtca** [comment]
Thanks, @ivirshup!
